# Generated by Django 5.0.3 on 2024-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogueitem",
            name="sku",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="content_type",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="data_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="source",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
