# Generated by Django 5.0.3 on 2024-04-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0002_catalogueitem_sku_alter_catalogueitem_content_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogueitem",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
